import {Expert} from '../types';

export const experts: Expert[] = [
  {
    username: 'desert_lens',
    nameFr: 'Jean Pierre Dupont',
    nameAr: 'جان بيير ديبون',
    domain: 'photographer',
    yearsOfExperience: 10,
    city: 'Atar',
    rating: 4.8,
    image: require('../assets/images/photography/1.jpg'),
  },
  {
    username: 'mauritanian_motion',
    nameFr: 'Aïcha Mint Ahmed',
    nameAr: 'عائشة منت أحمد',
    domain: 'videographer',
    yearsOfExperience: 5,
    city: 'Nouakchott',
    rating: 4.5,
    image: require('../assets/images/videography/1.jpg'),
  },
  {
    username: 'pixels_of_n',
    nameFr: 'Mohamed Ould Sidi',
    nameAr: 'محمد ولد سيدي',
    domain: 'graphic_designer',
    yearsOfExperience: 8,
    city: 'Zouérat',
    rating: 4.7,
    image: require('../assets/images/graphic_design/1.jpg'),
  },
  {
    username: 'sahara_images',
    nameFr: 'Isabelle Dubois',
    nameAr: 'إيزابيل دوبوا',
    domain: 'photographer',
    yearsOfExperience: 15,
    city: 'Aleg',
    rating: 4.9,
    image: require('../assets/images/photography/2.jpg'),
  },
  {
    username: 'visual_storyteller',
    nameFr: 'Omar Traoré',
    nameAr: 'عمر توري',
    domain: 'videographer',
    yearsOfExperience: 7,
    city: 'Nouadhibou',
    rating: 4.2,

    image: require('../assets/images/videography/2.jpg'),
  },
  {
    username: 'designbym',
    nameFr: 'Miriam Mint Mohamed',
    nameAr: 'مريم منت محمد',
    domain: 'graphic_designer',
    yearsOfExperience: 3,
    city: 'Kaédi',
    rating: 4.3,
    image: require('../assets/images/graphic_design/2.jpg'),
  },
  {
    username: 'desert_drone',
    nameFr: 'Pierre Durand',
    nameAr: 'بيير دوران',
    domain: 'videographer',
    yearsOfExperience: 12,
    city: 'Atar',
    rating: 4.6,
    image: require('../assets/images/videography/3.jpg'),
  },
  {
    username: 'akjoujt_arts',
    nameFr: 'Fatima Mint Cheikh',
    nameAr: 'فاطمة منت الشيخ',
    domain: 'graphic_designer',
    yearsOfExperience: 2,
    city: 'Akjoujt',
    rating: 4.4,
    image: require('../assets/images/graphic_design/3.jpg'),
  },
  {
    username: 'nomadic_lens',
    nameFr: 'Ahmed Fall',
    nameAr: 'أحمد فال',
    domain: 'photographer',
    yearsOfExperience: 20,
    city: 'Rosso',
    rating: 5.0,
    image: require('../assets/images/photography/3.jpg'),
  },
  {
    username: 'mauritania_edits',
    nameFr: 'Aminata Mint Baba',
    nameAr: 'أمينة منت بابا',
    domain: 'video_editor',
    yearsOfExperience: 4,
    city: 'Nouakchott',
    rating: 4.1,
    image: require('../assets/images/video_editing/1.jpg'),
  },
  {
    username: 'desert_frames',
    nameFr: 'Louis Lemaire',
    nameAr: 'لويس لومير',
    domain: 'photographer',
    yearsOfExperience: 8,
    city: 'Zouérat',
    rating: 4.7,
    image: require('../assets/images/photography/4.jpg'),
  },
  {
    username: 'nktt_motion',
    nameFr: 'Hawa Mint Abderrahmane',
    nameAr: 'حواء منت عبد الرحمن',
    domain: 'videographer',
    yearsOfExperience: 3,
    city: 'Rosso',
    rating: 4.2,
    image: require('../assets/images/videography/1.jpg'),
  },
  {
    username: 'kiffa_designs',
    nameFr: 'Mohamed Lemine Ould Mohamed',
    nameAr: 'محمد لمين ولد محمد',
    domain: 'graphic_designer',
    yearsOfExperience: 5,
    city: 'Kiffa',
    rating: 4.5,
    image: require('../assets/images/graphic_design/4.jpg'),
  },
  {
    username: 'visual_nomad',
    nameFr: 'Djibril Diallo',
    nameAr: 'جبريل ديالو',
    domain: 'photographer',
    yearsOfExperience: 12,
    city: 'Rosso',
    rating: 4.8,
    image: require('../assets/images/photography/1.jpg'),
  },
  {
    username: 'mauritania_cut',
    nameFr: 'Aïcha Mint Brahim',
    nameAr: 'عائشة منت ابراهيم',
    domain: 'video_editor',
    yearsOfExperience: 6,
    city: 'Nouadhibou',
    rating: 4.6,
    image: require('../assets/images/video_editing/2.jpg'),
  },
  {
    username: 'aleg_arts',
    nameFr: 'Sidi Mohamed Ould Ahmed',
    nameAr: 'سيدي محمد ولد أحمد',
    domain: 'graphic_designer',
    yearsOfExperience: 10,
    city: 'Aleg',
    rating: 4.9,
    image: require('../assets/images/graphic_design/1.jpg'),
  },
  {
    username: 'desert_stories',
    nameFr: 'Marie Durand',
    nameAr: 'ماري دوران',
    domain: 'videographer',
    yearsOfExperience: 18,
    city: 'Atar',
    rating: 5.0,
    image: require('../assets/images/videography/2.jpg'),
  },
  {
    username: 'nktt_designs',
    nameFr: 'Yacoub Ould Mohamed',
    nameAr: 'يعقوب ولد محمد',
    domain: 'graphic_designer',
    yearsOfExperience: 7,
    city: 'Nouakchott',
    rating: 4.3,
    image: require('../assets/images/graphic_design/2.jpg'),
  },
  {
    username: 'visual_explorer',
    nameFr: 'Mamadou Diallo',
    nameAr: 'مامادو ديالو',
    domain: 'photographer',
    yearsOfExperience: 15,
    city: 'Nouadhibou',
    rating: 4.7,
    image: require('../assets/images/photography/2.jpg'),
  },
  {
    username: 'mauritania_edits2',
    nameFr: 'Fatima Mint Mohamed',
    nameAr: 'فاطمة منت محمد',
    domain: 'video_editor',
    yearsOfExperience: 2,
    city: 'Nouakchott',
    rating: 4.0,
    image: require('../assets/images/video_editing/3.jpg'),
  },
];
