import {Expert} from '../types';

export const experts: Expert[] = [
  {
    nameFr: 'Karim Mohammed',
    nameAr: 'كريم محمد',
    username: 'karim_gfx',
    yearsOfExperience: 3,
    domain: 'graphic_designer',
    rating: 4.0,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Fatima bint Ahmed',
    nameAr: 'فاطمة بنت أحمد',
    username: 'fatima_photography',
    yearsOfExperience: 10,
    domain: 'photographer',
    rating: 4.9,
    image: require('../assets/images/photographer.jpg'),
  },
  {
    nameFr: 'Youssef Benali',
    nameAr: 'يوسف بن علي',
    username: 'youssef_media',
    yearsOfExperience: 7,
    domain: 'videographer',
    rating: 4.6,
    image: require('../assets/images/videographer.jpg'),
  },
  {
    nameFr: 'Leila Hassan',
    nameAr: 'ليلى حسن',
    username: 'leila_vedit',
    yearsOfExperience: 2,
    domain: 'video_editor',
    rating: 4,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Youssef Ali',
    nameAr: 'إبراهيم سو',
    username: 'isow_gfx',
    yearsOfExperience: 4,
    domain: 'graphic_designer',
    rating: 4.2,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Mounia Camara',
    nameAr: 'مونيا كمارا',
    username: 'mounia_arts',
    yearsOfExperience: 6,
    domain: 'graphic_designer',
    rating: 4.5,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Omar Aziz',
    nameAr: 'عمر عزيز',
    username: 'omarz.photography',
    yearsOfExperience: 11,
    domain: 'photographer',
    rating: 4.9,
    image: require('../assets/images/photographer2.jpg'),
  },
  {
    nameFr: 'Aïcha Bah',
    nameAr: 'عائشة باه',
    username: 'aicha_media',
    yearsOfExperience: 5,
    domain: 'videographer',
    rating: 4.4,
    image: require('../assets/images/videographer.jpg'),
  },

  {
    nameFr: 'Sarah Mohamed',
    nameAr: 'سارة محمد',
    username: 'sarah_graphicdesign',
    yearsOfExperience: 3,
    domain: 'graphic_designer',
    rating: 4.1,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Ahmed Benali',
    nameAr: 'أحمد بن علي',
    username: 'gfx.ahmed',
    yearsOfExperience: 7,
    domain: 'graphic_designer',
    rating: 4.4,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Fatima bint Hassan',
    nameAr: 'فاطمة بنت حسن',
    username: 'fatima_photography_',
    yearsOfExperience: 9,
    domain: 'photographer',
    rating: 4.8,
    image: require('../assets/images/photographer.jpg'),
  },
  {
    nameFr: 'Youssef Sow',
    nameAr: 'يوسف سو',
    username: 'youssef_media_pro',
    yearsOfExperience: 4,
    domain: 'videographer',
    rating: 4.2,
    image: require('../assets/images/videographer.jpg'),
  },
];
