import {Expert} from '../types';

export const experts: Expert[] = [
  {
    nameFr: 'Omar Khaled',
    nameAr: 'عمر خالد',
    username: 'omarkhaled_dev',
    yearsOfExperience: 8,
    profession: 'software_developer',
    rating: 4.8,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Aïcha Diallo',
    nameAr: 'عائشة ديالو',
    username: 'designbyaisha',
    yearsOfExperience: 5,
    profession: 'web_designer',
    rating: 4.5,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Karim Mohammed',
    nameAr: 'كريم محمد',
    username: 'karim_gfx',
    yearsOfExperience: 3,
    profession: 'graphic_designer',
    rating: 4.0,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Fatima bint Ahmed',
    nameAr: 'فاطمة بنت أحمد',
    username: 'fatima_photography',
    yearsOfExperience: 10,
    profession: 'photographer',
    rating: 4.9,
    image: require('../assets/images/photographer.jpg'),
  },
  {
    nameFr: 'Youssef Benali',
    nameAr: 'يوسف بن علي',
    username: 'youssef_media',
    yearsOfExperience: 7,
    profession: 'videographer',
    rating: 4.6,
    image: require('../assets/images/videographer.jpg'),
  },
  {
    nameFr: 'Leila Hassan',
    nameAr: 'ليلى حسن',
    username: 'leila_dev',
    yearsOfExperience: 2,
    profession: 'software_developer',
    rating: 4,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Ibrahim Sow',
    nameAr: 'إبراهيم سو',
    username: 'isow_design',
    yearsOfExperience: 4,
    profession: 'web_designer',
    rating: 4.2,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Mounia Camara',
    nameAr: 'مونيا كمارا',
    username: 'mounia_arts',
    yearsOfExperience: 6,
    profession: 'graphic_designer',
    rating: 4.5,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Omar Aziz',
    nameAr: 'عمر عزيز',
    username: 'omarz.photography',
    yearsOfExperience: 11,
    profession: 'photographer',
    rating: 4.9,
    image: require('../assets/images/photographer2.jpg'),
  },
  {
    nameFr: 'Aïcha Bah',
    nameAr: 'عائشة باه',
    username: 'aicha_media',
    yearsOfExperience: 5,
    profession: 'videographer',
    rating: 4.4,
    image: require('../assets/images/videographer.jpg'),
  },
  {
    nameFr: 'Khaled Diallo',
    nameAr: 'خالد ديالو',
    username: 'khaled_dev',
    yearsOfExperience: 1,
    profession: 'software_developer',
    rating: 3.9,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Sarah Binta Mohammed',
    nameAr: 'سارة بنت محمد',
    username: 'sarah_webdesign',
    yearsOfExperience: 3,
    profession: 'web_designer',
    rating: 4.1,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Ahmed Benali',
    nameAr: 'أحمد بن علي',
    username: 'gfx.ahmed',
    yearsOfExperience: 7,
    profession: 'graphic_designer',
    rating: 4.4,
    image: require('../assets/images/designer.jpg'),
  },
  {
    nameFr: 'Fatima bint Hassan',
    nameAr: 'فاطمة بنت حسن',
    username: 'fatima_photography_',
    yearsOfExperience: 9,
    profession: 'photographer',
    rating: 4.8,
    image: require('../assets/images/photographer.jpg'),
  },
  {
    nameFr: 'Youssef Sow',
    nameAr: 'يوسف سو',
    username: 'youssef_media_pro',
    yearsOfExperience: 4,
    profession: 'videographer',
    rating: 4.2,
    image: require('../assets/images/videographer.jpg'),
  },
  {
    nameFr: 'Leila Camara',
    nameAr: 'ليلى كمارا',
    username: 'leila.dev',
    yearsOfExperience: 6,
    profession: 'software_developer',
    rating: 4.7,
    image: require('../assets/images/developer.jpg'),
  },
  {
    nameFr: 'Ibrahim Aziz',
    nameAr: 'إبراهيم عزيز',
    username: 'iaziz_design',
    yearsOfExperience: 2,
    profession: 'web_designer',
    rating: 4.3,
    image: require('../assets/images/developer.jpg'),
  },
];
